# Generated by Django 4.2.4 on 2023-08-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital', models.CharField(blank=True, max_length=20, null=True)),
                ('first_appearance', models.CharField(blank=True, max_length=100)),
                ('last_appearance', models.CharField(blank=True, max_length=100)),
                ('actor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('air_date', models.DateField()),
                ('episode_number', models.IntegerField()),
                ('series_episode_number', models.IntegerField()),
                ('main_characters', models.ManyToManyField(blank=True, related_name='main_episodes', to='api.character')),
                ('recurring_characters', models.ManyToManyField(blank=True, related_name='recurring_episodes', to='api.character')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.season')),
                ('supporting_characters', models.ManyToManyField(blank=True, related_name='supporting_episodes', to='api.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='characters', to='api.job'),
        ),
        migrations.AddField(
            model_name='character',
            name='workplace',
            field=models.ManyToManyField(blank=True, related_name='characters', to='api.workplace'),
        ),
    ]
